version: "3.8"

services:
  backend:
    build: .
    container_name: sispar_backend
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    env_file:
      - .env
    depends_on:
      - sispar-db
    command: /bin/sh -c "sleep 20 && python run.py"

  sispar-db:
    image: mysql:8.0
    container_name: sispar-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sispar
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
